"""adding last_week_closing_price col

Revision ID: 0a34a0cf0922
Revises: 4ee47da0e811
Create Date: 2024-04-03 14:00:24.184436

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a34a0cf0922"
down_revision: Union[str, None] = "4ee47da0e811"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analysis_currency_stage_one",
        sa.Column("last_week_closing_price", sa.NUMERIC(precision=15, scale=8), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analysis_currency_stage_one", "last_week_closing_price")
    # ### end Alembic commands ###
