"""New column Current Price AutoRegenerate

Revision ID: 2c8af520be61
Revises: 1815e89d29cf
Create Date: 2024-04-02 23:04:42.061251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c8af520be61'
down_revision: Union[str, None] = '1815e89d29cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency_base_info', sa.Column('current_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currency_base_info', 'current_price')
    # ### end Alembic commands ###
