"""adding table rel. analysis_first_stage

Revision ID: 331dd4b041d1
Revises: d4f27fd7fba0
Create Date: 2024-03-29 21:08:34.179691

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "331dd4b041d1"
down_revision: Union[str, None] = "d4f27fd7fba0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "analysis_currency_stage_one_uuid_analysis_fkey", "analysis_currency_stage_one", type_="foreignkey"
    )
    op.drop_column("analysis_currency_stage_one", "uuid_analysis")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analysis_currency_stage_one", sa.Column("uuid_analysis", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        "analysis_currency_stage_one_uuid_analysis_fkey",
        "analysis_currency_stage_one",
        "analysis",
        ["uuid_analysis"],
        ["uuid"],
    )
    # ### end Alembic commands ###
