"""roll back: adding table rel. analysis_first_stage

Revision ID: 513b0342d6a8
Revises: ab894cb28dd0
Create Date: 2024-03-29 21:21:20.599121

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "513b0342d6a8"
down_revision: Union[str, None] = "ab894cb28dd0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_currency_stage_one",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("uuid_analysis", sa.UUID(), nullable=True),
        sa.Column("uuid_currency", sa.UUID(), nullable=True),
        sa.Column("ranking", sa.Integer(), nullable=True),
        sa.Column("market_value", sa.NUMERIC(precision=15, scale=8), nullable=True),
        sa.Column("week_increase_percentage", sa.NUMERIC(precision=15, scale=8), nullable=True),
        sa.Column("increase_date", sa.DateTime(), nullable=True),
        sa.Column("closing_price", sa.NUMERIC(precision=15, scale=8), nullable=True),
        sa.Column("open_price", sa.NUMERIC(precision=15, scale=8), nullable=True),
        sa.Column("ema8", sa.NUMERIC(precision=15, scale=8), nullable=True),
        sa.Column("ema8_greater_open", sa.Boolean(), nullable=True),
        sa.Column("ema8_less_close", sa.Boolean(), nullable=True),
        sa.Column("week_increase_volume", sa.NUMERIC(precision=15, scale=8), nullable=True),
        sa.Column("increase_volume_day", sa.DateTime(), nullable=True),
        sa.Column("day_before_volume", sa.NUMERIC(precision=15, scale=8), nullable=True),
        sa.Column("volumes_relation", sa.NUMERIC(precision=15, scale=8), nullable=True),
        sa.Column("expressive_volume_increase", sa.Boolean(), nullable=True),
        sa.Column("ema_aligned", sa.Boolean(), nullable=True),
        sa.Column("buying_signal", sa.Boolean(), nullable=True),
        sa.Column("today", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["uuid_analysis"],
            ["analysis.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["uuid_currency"],
            ["currency_base_info.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("analysis_currency_stage_one")
    # ### end Alembic commands ###
