"""schedule table

Revision ID: 5378af3a4474
Revises: e3f73a5e0934
Create Date: 2024-04-01 10:35:31.280196

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5378af3a4474"
down_revision: Union[str, None] = "e3f73a5e0934"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currencies_info_schedule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("last_update_time", sa.DateTime(), nullable=True),
        sa.Column("next_scheduled_time", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_currencies_info_schedule_id"), "currencies_info_schedule", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_currencies_info_schedule_id"), table_name="currencies_info_schedule")
    op.drop_table("currencies_info_schedule")
    # ### end Alembic commands ###
