"""adding table rel. analysis_first_stage

Revision ID: 74afdc2b1669
Revises: 331dd4b041d1
Create Date: 2024-03-29 21:09:32.040717

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "74afdc2b1669"
down_revision: Union[str, None] = "331dd4b041d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_first_stage",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("uuid_analysis", sa.UUID(), nullable=True),
        sa.Column("uuid_analysis_currency_stage_one", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["uuid_analysis"],
            ["analysis.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["uuid_analysis_currency_stage_one"],
            ["analysis_currency_stage_one.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("analysis_first_stage")
    # ### end Alembic commands ###
