"""roll back: adding table rel. analysis_first_stage

Revision ID: ab894cb28dd0
Revises: 74afdc2b1669
Create Date: 2024-03-29 21:20:25.738801

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab894cb28dd0"
down_revision: Union[str, None] = "74afdc2b1669"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("analysis_first_stage")
    op.add_column("analysis_currency_stage_one", sa.Column("uuid_analysis", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "analysis_currency_stage_one", "analysis", ["uuid_analysis"], ["uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "analysis_currency_stage_one", type_="foreignkey")
    op.drop_column("analysis_currency_stage_one", "uuid_analysis")
    op.create_table(
        "analysis_first_stage",
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("uuid_analysis", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("uuid_analysis_currency_stage_one", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["uuid_analysis"], ["analysis.uuid"], name="analysis_first_stage_uuid_analysis_fkey"),
        sa.ForeignKeyConstraint(
            ["uuid_analysis_currency_stage_one"],
            ["analysis_currency_stage_one.uuid"],
            name="analysis_first_stage_uuid_analysis_currency_stage_one_fkey",
        ),
        sa.PrimaryKeyConstraint("uuid", name="analysis_first_stage_pkey"),
    )
    # ### end Alembic commands ###
