"""adding today to FirstStageAnalysis

Revision ID: d4f27fd7fba0
Revises: bac1c4f9d445
Create Date: 2024-03-29 21:01:23.281165

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4f27fd7fba0"
down_revision: Union[str, None] = "bac1c4f9d445"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("analysis_currency_stage_one", sa.Column("today", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analysis_currency_stage_one", "today")
    # ### end Alembic commands ###
